apiVersion: v1
kind: Service
metadata:
  name: go-http
  namespace: default   # <--- EZT IS ADD HOZZÃ
  labels:
    app: go-http
spec:
  selector:
    app: go-http
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
